# Generated by Django 3.2.15 on 2022-08-19 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(help_text='Descriptive name for this job', max_length=256)),
                ('schedule', models.CharField(help_text='Job schedule (crontab format)', max_length=64)),
                ('deadline', models.IntegerField(default=5, help_text='The deadline in minutes after the scheduled time in which a job should be completed')),
                ('status', models.CharField(help_text='Expected status value for job instances', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_good', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_notify', models.DateTimeField(blank=True, editable=False, null=True)),
                ('workflow_check_result', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('owner', models.ForeignKey(help_text='Job owner (destination for notifications)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='JobInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(max_length=256)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsy.job')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
