# Generated by Django 3.2.15 on 2022-09-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, help_text='Job URL', max_length=2048, null=True),
        ),
    ]
